worker_processes  1;

events {
    worker_connections  1024;
}


http {
	server_names_hash_bucket_size  64;
    server_tokens off;
    include       mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';
	
	server {
		listen       80;
		server_name  bestserverever.com;
		root /usr/share/nginx/html;
		
		if ($request_method !~ ^(GET|HEAD|POST)$ ) {
                return 405;
            }
		
		index index.html;
		
		
#       kill cache
# 		add_header Last-Modified $date_gmt;
# 		add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
# 		if_modified_since off;
# 		expires off;
# 		etag off;
		
	}

		

    server {
		listen       80;
		server_name  telegram.bestserverever.com;

		
		client_body_buffer_size 1K;
		client_header_buffer_size 1k;
		client_max_body_size 10m;
		large_client_header_buffers 2 1k;

		location / {
            if ($request_method !~ ^(GET|POST)$ ) {
                return 405;
            }

            proxy_pass http://telegrambot:8881;
		}
	}
		
	
    


}